# file: roles/init/tasks/main.yml
---

# - name: Set up firewall
#   shell: systemctl enable firewalld

# - name: Start the firewall
#   shell: systemctl start firewalld

- name: Update Yum
  yum: name=* state=latest

- name: Install nano, git, etc
  yum: pkg={{ item }} state=installed
  with_items:
     - git
     # - firewalld
     - dumb-init
     - httpd
     - curl
     - gcc
     - kernel-devel
     - wget
     - vim
     - man
     - unzip
     - mod_ssl

- name: Copy the apache configuration
  copy:
    src: laravel-helloworld.conf
    dest: /etc/httpd/conf.d/laravel-helloworld.conf
    owner: apache
    group: root
    mode: 655
